/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMdiPause: typeof import('~icons/mdi/pause.jsx').default
  const IconMdiPlay: typeof import('~icons/mdi/play.jsx').default
  const IconMdiStop: typeof import('~icons/mdi/stop.jsx').default
}
